# Generated by Django 2.0.13 on 2021-09-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badukapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AddField(
            model_name='post',
            name='path',
            field=models.FileField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='GUEST', max_length=100),
        ),
    ]
