# Generated by Django 2.0.13 on 2021-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badukapp', '0002_auto_20210904_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='path',
            field=models.FileField(default='../static/img/no_image.jpg', upload_to='img'),
        ),
    ]
