# Generated by Django 2.0.13 on 2021-12-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badukapp', '0003_auto_20210908_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='내용없음'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='제목없음', max_length=200),
        ),
    ]
